import { TextEdit, Button } from "std-widgets.slint";

export component Label {
    in property <string> text;
    min-height: 24px;
    min-width: 100px;
    Text {
        text: root.text;
        color: black;
    }
}

export component CustomButton {
    in property <string> text;
    in property <bool> enabled: true;
    callback clicked();
    
    Button {
        text: root.text;
        width: 100px;
        height: 32px;
        clicked => { root.clicked() }
        enabled: root.enabled;
    }
}

export component CustomTextEdit {
    in property <string> placeholder-text: "";
    in property <bool> read-only: false;
    in-out property <string> text;
    
    TextEdit {
        height: 240px;
        width: 500px;
        text <=> root.text;
        read-only: root.read-only;
        placeholder-text: root.placeholder-text;
    }
} 