export component SingleLineEdit {
    in-out property <string> text;
    in property <bool> read-only;
    in property <string> placeholder-text;
    in property <brush> background;

    Rectangle {
        height: 36px;
        background: root.background;
        border-width: 1px;
        border-color: #E0E0E0;
        border-radius: 4px;
        clip: true;

        if text == "" && !read-only: Text {
            x: 8px;
            color: #9E9E9E;
            text: root.placeholder-text;
            font-size: 14px;
            vertical-alignment: center;
            height: parent.height;
        }

        TextInput {
            x: 8px;
            width: parent.width - 16px;
            height: parent.height;
            text <=> root.text;
            read-only: root.read-only;
            font-size: 14px;
            vertical-alignment: center;
        }
    }
} 