import { Styles } from "../themes/styles.slint";
import { Colors } from "../themes/colors.slint";
import { Fonts } from "../themes/fonts.slint";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";

// 网格布局
export component GridLayout {
    in property <length> spacing: Styles.spacing-normal;

    VerticalBox {
        spacing: root.spacing;
        alignment: start;

        @children
    }
}

// 网格行
export component GridRow {
    in property <length> spacing: Styles.spacing-normal;

    HorizontalBox {
        spacing: root.spacing;
        alignment: start;

        @children
    }
}

// 网格项
export component GridItem {
    in property <string> title;
    in property <string> description;

    VerticalBox {
        spacing: Styles.spacing-small;
        padding: Styles.spacing-small;

        if root.title != "" : Text {
            text: root.title;
            font-size: Fonts.size-normal;
            font-weight: Fonts.weight-medium;
            color: Colors.text;
        }

        if root.description != "" : Text {
            text: root.description;
            font-size: Fonts.size-small;
            color: Colors.text-secondary;
        }

        @children
    }
}
